sudo: true

language: python
python:
#  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install ."
services:
  - mysql
addons:
  postgresql: "9.5"
  
before_script:
 - cp tests/test.yaml ~/.pg_chameleon/connection/
 - psql -c "create user usr_test with password 'test';" -U postgres
 - psql -c 'create database db_test with owner usr_test;' -U postgres

 # command to run tests
script: tests/test_build.py

