sudo: true

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# install pg_chameleon
install: "pip install ."

services:
  - mysql

env:
   - MYVER='55'

addons:
  postgresql: "9.5"
  
before_script:
 - tests/setup_db.sh
 
 # command to run tests
script: tests/test.sh

