---

replica1:
  mysql_conn:
      host: localhost
      port: 3306
      user: replication_username
      passwd: never_commit_passwords
      my_server_id: 100
      my_database:  db_replica
      my_charset: 'utf8'


  #postgres connection
  pg_conn:
      host: localhost
      port: 5432
      user: replication_username
      password: never_commit_passwords
      pg_database: db_replication
      pg_charset: 'utf8'
      destination_schema: sch_replica

  tables_limit:
  replica_batch_size: 1000
  copy_max_memory: 300M
  copy_mode: 'file'
