---
replica_batch_size: 1000
copy_max_memory: 300M
copy_mode: 'file'
hexify: 
    - 'blob'
    - 'tinyblob'
    - 'mediumblob'
    - 'longblob'
    - 'binary'

 
pid_dir: 'pid/'


log_dir: 'logs/'
log_level: 'debug'
log_dest: 'stdout'

#seconds between each replica loop
sleep_loop: 10 

#Pause the replica for the given amount of seconds if a reindex process is found
pause_on_reindex: Yes
sleep_on_reindex: 30


#list the application names which are supposed to reindex the database
reindex_app_names:
    - 'reindexdb'
    - 'my_custom_reindex'

connections:
  replica1:
    src_conn:
        host: localhost
        port: 3306
        user: usr_replica
        passwd: never_commit_passwords
        replica_slot: 100
        replica_database:  db_replica
        src_schema: #same as replica_database if type mysql
        my_charset: 'utf8'
        type: 'mysql'

    dest_conn:
        host: construct
        port: 5432
        user: usr_replica
        password: never_commit_passwords
        pg_database: db_replication
        pg_charset: 'utf8'
        destination_schema: sch_replica
    
